knp_doctrine_behaviors:
    blameable:      true
    geocodable:     ~     # Here null is converted to false
    loggable:       ~
#    sluggable:      true
    soft_deletable: true
    translatable: true
    tree: true
    timestampable: true
    # All others behaviors are disabled